name: 'Run Airflow DAG'
description: 'Trigger a DAG run and wait for completion'
inputs:
  airflow_url:       { required: true,  description: 'Base URL' }
  dag_id:            { required: true,  description: 'DAG ID' }
  username:          { required: true,  description: 'User' }
  password:          { required: true,  description: 'Password' }
  timeout_minutes:   { required: false, default: '15',
                       description: 'Max minutes to wait for success' }
runs:
  using: composite
  steps:
    - uses: actions/setup-python@v5
      with: { python-version: '3.11' }

    - run: pip install requests

    - run: python ${{ github.action_path }}/run_airflow_dag.py
      env:
        AIRFLOW_URL:    ${{ inputs.airflow_url }}
        DAG_ID:         ${{ inputs.dag_id }}
        USERNAME:       ${{ inputs.username }}
        PASSWORD:       ${{ inputs.password }}
        TIMEOUT_MINUTES:${{ inputs.timeout_minutes }}
