name: 'Run Airflow DAG'
description: 'Trigger and monitor an Airflow DAG via REST API'
inputs:
  airflow_url:
    required: true
    description: 'Airflow base URL'
  dag_id:
    required: true
    description: 'DAG ID'
  username:
    required: true
    description: 'Airflow username'
  password:
    required: true
    description: 'Airflow password'
  timeout_minutes:
    required: false
    default: '15'
    description: 'Timeout in minutes'

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install requests
    - name: Run Airflow DAG
      env:
        AIRFLOW_URL: ${{ inputs.airflow_url }}
        DAG_ID: ${{ inputs.dag_id }}
        USERNAME: ${{ inputs.username }}
        PASSWORD: ${{ inputs.password }}
        TIMEOUT_MINUTES: ${{ inputs.timeout_minutes }}
      run: python ${{ github.action_path }}/run_airflow_dag.py
